- name: Upgrade apt
  become: true
  apt:
      upgrade: yes

- name: Install npm
  become: yes
  apt:
    name: npm
    update_cache: yes
    state: latest

- name: Install nodejs
  become: yes
  apt:
    name: nodejs
    update_cache: yes
    state: latest    

- name: Install pm2
  become: yes
  npm:
    name: pm2
    state: present
    global: yes
