- name: copy backend files to server
  become: true
  copy:
      src: ~/project/artifact.tar.gz
      dest: /home/ubuntu/artifact.tar.gz
- name: start server
  shell: |
      echo "START EXTRACT"
      cd /home/ubuntu
      tar -xzvf artifact.tar.gz -C .
      #add .env
      echo ENVIRONMENT=production >> ".env"
      echo NODE_ENV=production >> ".env"
      echo TYPEORM_CONNECTION=postgres >> ".env"
      echo TYPEORM_MIGRATIONS_DIR=./src/migrations >> ".env"
      echo TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts >> ".env"
      echo TYPEORM_MIGRATIONS=./src/migrations/*.ts >> ".env"
      echo TYPEORM_HOST=$TYPEORM_HOST >> ".env"
      echo TYPEORM_PORT=$TYPEORM_PORT >> ".env"
      echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> ".env"
      echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> ".env"
      echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> ".env"
      sudo npm install
      sudo npm run build
      sudo pm2 stop default
      sudo pm2 start npm --name 'udapeople' -- start
      cd dist
      sudo pm2 start main.js
      sudo pm2 log