- name: copy backend files to server
  become: true
  copy:
      src: ~/project/artifact.tar.gz
      dest: /home/ubuntu/artifact.tar.gz
- name: start server
  shell: |
      cd /home/ubuntu/
      tar -xzvf artifact.tar.gz -C .
      sudo npm install
      sudo npm run build
      sudo pm2 start npm backend -- start