- name: copy backend files to server
  become: true
  copy:
      src: /root/project/artifact.tar.gz
      dest: /home/ubuntu
- name: start server
  shell: |
      cd /home/ubuntu/
      tar -xzvf artifact.tar.gz -C backend
      cd backend
      sudo npm install
      sudo npm run build
      cd dist
      sudo pm2 stop default
      sudo pm2 start npm backend -- start